name: Deploy to stage

# Trigger the workflow on push and
# pull request events on the production branch
on:
    push:
        branches:
            - develop

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Deploy to testing
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                    cd /home/${{ secrets.USERNAME }}/websites/stage/stage.psoni-staszow.pl
                    pwd
                    /home/${{ secrets.USERNAME }}
                    cd /home/${{ secrets.USERNAME }}/websites/stage/stage.psoni-staszow.pl /deploy.sh