name: Deploy to stage
on:
    push:
        branches:
            - develop
jobs:
    deploy-to-stage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - run: 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
            - run: 'composer -V'
            - run: 'php -v'
            - run: |
                  ssh mateuszr84@atthost24.pl -p 6022 \
                  ' \
                    /home/mateuszr84/bin/deploy_scripts/phenomenon/scripts/new-release.sh \
                      "Psoni stage" \
                      "/home/mateuszr84/websites/testing/test.psoni-staszow.pl" \
                      "${ secrets.LICENSE_KEY }" \
                      "git@github.com:mateuszR84/psoni.git" \
                      "develop" \
                      "/home/mateuszr84/websites/testing/test.psoni-staszow.pl/linked" \
                      "storage|.env|.htaccess" \
                      "https://github.com/help" \
                      "3.6" \
                  '